# -*- coding: utf-8 -*-
"""EstruturaCNAE.ipynb

Automatically generated by Colaboratory.
"""

import requests
import pandas as pd

api = "https://servicodados.ibge.gov.br/api/v2/cnae/subclasses"
response = requests.get(api)
df = pd.DataFrame(response.json())
df.head()

# Normalizing JSON file
df = pd.json_normalize(response.json(), meta='classe')
df.head()

# list columns
df.columns

# remove columns
df["TextoCNAE"] = df["descricao"]
df = df.drop(columns=['atividades', 'observacoes', 'classe.observacoes'])
df.head()


# Rename columns based on CNAE Structure, where subclass concept of CNAE
df.rename(columns={'classe.grupo.divisao.secao.id': 'IdSecao',
                   'classe.grupo.divisao.secao.descricao': 'DescricaoSecao',
                   'classe.grupo.divisao.id': 'IdDivisao',
                   'classe.grupo.divisao.descricao': 'DescricaoDivisao',
                   'classe.grupo.id': 'IdGrupo',
                   'classe.grupo.descricao': 'DescricaoGrupo',
                   'classe.id': 'IdClasse',
                   'classe.descricao': 'DescricaoClasse',
                   'id': 'IdCNAE',
                   'descricao': 'DescricaoCNAE'
                   }, inplace=True)

# Reorganizing columns -> CNAE represents Subclass
df = df[['IdCNAE', 'DescricaoCNAE', 'TextoCNAE',
         'IdClasse', 'DescricaoClasse', 'IdGrupo', 'DescricaoGrupo',
         'IdDivisao', 'DescricaoDivisao', 'IdSecao', 'DescricaoSecao']]

# df

# Set dtype for column values
df['IdDivisao'] = df['IdDivisao'].astype(int)
df['IdGrupo'] = df['IdGrupo'].astype(int)
df['IdClasse'] = df['IdClasse'].astype(int)
df['IdCNAE'] = df['IdCNAE'].astype(int)
df.dtypes

df.sort_values(by=['IdCNAE'], inplace=True)
# df

df = df.reset_index(drop=True)
df.head()

# Unindo ids aos valores de descrição
df["DescricaoDivisao"] = df["IdDivisao"].astype(str)+"-"+df["DescricaoDivisao"]
df["DescricaoGrupo"] = df["IdGrupo"].astype(str)+"-"+df["DescricaoGrupo"]
df["DescricaoClasse"] = df["IdClasse"].astype(str)+"-"+df["DescricaoClasse"]
df["DescricaoCNAE"] = df["IdCNAE"].astype(str)+"-"+df["DescricaoCNAE"]
df = df.drop_duplicates()
# df


df.to_excel('DimCNAE.xlsx', index=False, encoding='utf-8')
